name: Build and deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - website-migration
jobs:
  build-deploy:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker run --privileged -i --rm -p 4000:4000 -e LC_ALL=C.UTF-8 -e LANG=C.UTF-8 -v $(pwd):/site debezium/website-builder rake clean build
      
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.PUBLISH_GH_TOKEN }}
        with:
          target_branch: 'master'