name: Build and deploy to GitHub Pages

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - website-migration
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker pull antora/antora:2.3.0-alpha.2
      - name: Build
        run: docker run -it --rm --privileged --user=$UID:$UID -v $(pwd):/site -w="/site" antora/antora:2.3.0-alpha.2 --cache-dir=./_antora_cache --stacktrace playbook.yml
      - uses: ls -la ./_antora_cache/content
      - uses: rm -rf ./_antora_cache
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@2.0.4
        env:
          JEKYLL_PAT: ${{ secrets.PUBLISH_GH_TOKEN }}
