name: Testing the GitHub Pages publication

on:
  push

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2

    - name: 🎩 Install Jekyll
      run: |
        gem install bundler jekyll
        bundle install    

    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    # Specify the Jekyll source location as a parameter
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.PUBLISH_GH_TOKEN }}
        jekyll_src: './_site'

    # Specify the target branch (optional)
    - uses: helaili/jekyll-action@v2
      with:
        token: ${{ secrets.PUBLISH_GH_TOKEN }}
        target_branch: 'master'