name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - develop
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUBLISH_GH_TOKEN}}
          publish_dir: ./_site
          publish_branch: master    