name: 'teardown'
on: # rebuild any PRs and main branch changes
  pull_request:
    # use default types + closed event type
    types: [closed]
jobs:
  preview: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: preview_step
        name: test afc163/surge-preview
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          teardown: 'true'
          failOnError: 'false'
          # dist: _site/
          build: |
            echo Deleting from surge.sh
